version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  setup:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls ~/project
      - run:
          command: mkdir build && touch build/hello.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls ~/project
      - run:
          name: Greeting
          command: echo Hello, world. $CIRCLE_TAG
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - setup:
          filters:
            tags:
              ignore: /^.*/
      - build:
          filters:
            tags:
              ignore: /^.*/
          requires:
              - setup
  tagged-build:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
