version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  setup:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls ~/project
      - run:
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls ~/project
      - run:
          command: npm test

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls ~/project
      - run:
          command: ls ~/project/build

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - test:
          requires:
              - setup
      - build:
          requires:
              - setup
      - deploy:
          requires:
              - build

