version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.4
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

  deploy:
    docker:
      - image: circleci/node:6.11.4
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world. $CIRCLE_TAG
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^.*/
  tagged-build:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
